/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as ProfileSettingsImport } from './routes/profile/settings'
import { Route as ProfileScheduleImport } from './routes/profile/schedule'
import { Route as ProfileMessagesImport } from './routes/profile/messages'
import { Route as ProfileGradesImport } from './routes/profile/grades'
import { Route as ProfileCoursesImport } from './routes/profile/courses'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProfileScheduleRoute = ProfileScheduleImport.update({
  id: '/profile/schedule',
  path: '/profile/schedule',
  getParentRoute: () => rootRoute,
} as any)

const ProfileMessagesRoute = ProfileMessagesImport.update({
  id: '/profile/messages',
  path: '/profile/messages',
  getParentRoute: () => rootRoute,
} as any)

const ProfileGradesRoute = ProfileGradesImport.update({
  id: '/profile/grades',
  path: '/profile/grades',
  getParentRoute: () => rootRoute,
} as any)

const ProfileCoursesRoute = ProfileCoursesImport.update({
  id: '/profile/courses',
  path: '/profile/courses',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/profile/courses': {
      id: '/profile/courses'
      path: '/profile/courses'
      fullPath: '/profile/courses'
      preLoaderRoute: typeof ProfileCoursesImport
      parentRoute: typeof rootRoute
    }
    '/profile/grades': {
      id: '/profile/grades'
      path: '/profile/grades'
      fullPath: '/profile/grades'
      preLoaderRoute: typeof ProfileGradesImport
      parentRoute: typeof rootRoute
    }
    '/profile/messages': {
      id: '/profile/messages'
      path: '/profile/messages'
      fullPath: '/profile/messages'
      preLoaderRoute: typeof ProfileMessagesImport
      parentRoute: typeof rootRoute
    }
    '/profile/schedule': {
      id: '/profile/schedule'
      path: '/profile/schedule'
      fullPath: '/profile/schedule'
      preLoaderRoute: typeof ProfileScheduleImport
      parentRoute: typeof rootRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile/courses': typeof ProfileCoursesRoute
  '/profile/grades': typeof ProfileGradesRoute
  '/profile/messages': typeof ProfileMessagesRoute
  '/profile/schedule': typeof ProfileScheduleRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile/courses': typeof ProfileCoursesRoute
  '/profile/grades': typeof ProfileGradesRoute
  '/profile/messages': typeof ProfileMessagesRoute
  '/profile/schedule': typeof ProfileScheduleRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile/courses': typeof ProfileCoursesRoute
  '/profile/grades': typeof ProfileGradesRoute
  '/profile/messages': typeof ProfileMessagesRoute
  '/profile/schedule': typeof ProfileScheduleRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile/courses'
    | '/profile/grades'
    | '/profile/messages'
    | '/profile/schedule'
    | '/profile/settings'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile/courses'
    | '/profile/grades'
    | '/profile/messages'
    | '/profile/schedule'
    | '/profile/settings'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile/courses'
    | '/profile/grades'
    | '/profile/messages'
    | '/profile/schedule'
    | '/profile/settings'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileCoursesRoute: typeof ProfileCoursesRoute
  ProfileGradesRoute: typeof ProfileGradesRoute
  ProfileMessagesRoute: typeof ProfileMessagesRoute
  ProfileScheduleRoute: typeof ProfileScheduleRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileCoursesRoute: ProfileCoursesRoute,
  ProfileGradesRoute: ProfileGradesRoute,
  ProfileMessagesRoute: ProfileMessagesRoute,
  ProfileScheduleRoute: ProfileScheduleRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/profile/courses",
        "/profile/grades",
        "/profile/messages",
        "/profile/schedule",
        "/profile/settings",
        "/profile/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/profile/courses": {
      "filePath": "profile/courses.tsx"
    },
    "/profile/grades": {
      "filePath": "profile/grades.tsx"
    },
    "/profile/messages": {
      "filePath": "profile/messages.tsx"
    },
    "/profile/schedule": {
      "filePath": "profile/schedule.tsx"
    },
    "/profile/settings": {
      "filePath": "profile/settings.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
